version: "3.8"

services:
  weewx:
    image: localhost/weewx:debian-latest
    container_name: weewx
#    init: true
    restart: "unless-stopped"
#    user: root
    networks:
      - podman
    ports:
      - 8080:8080 # Must be exposed to make it accessible on the host
    volumes:
      - ~/containers/config/weewx:/etc/weewx
      - ~/containers/data/weewx:/home/weewx
    env_file:
      - .env
    environment:
      - TIMEZONE=UTC
      - ENABLE_INFINITE_LOOP=no # Set yes for debugging purposes
#      - WEEWX_UID=root
#      - WEEWX_GID=root
#    devices:
#      - "/dev/ttyUSB0:/dev/ttyUSB0"

networks:
  podman:
    external: true
