FROM localhost/weewx-base:alpine-latest

ARG WEEWX_VERSION="4.10.2" # Latest supported by the extensions
#ARG WEEWX_VERSION="5.0.2" # ** This breaks the extensions **

ARG WEEWX_PATH="/opt/weewx"
#ARG WEEWX_HOME_DIR="/home/weewx"
ARG WEEWX_CONF_PATH="/etc/weewx"
ARG VENV_PATH="/opt/venv"
ARG PATCHES_PATH="/opt/patches"

# Create Directories
RUN mkdir -p "${WEEWX_PATH}"
RUN mkdir -p "${WEEWX_CONF_PATH}"
RUN mkdir -p "${VENV_PATH}"
RUN mkdir -p "${PATCHES_PATH}"

# Change Directory and Copy requirements.txt
#WORKDIR "/opt"
COPY requirements.txt "${WEEWX_PATH}/requirements.txt"
COPY patches/* "${PATCHES_PATH}"

# Create venv
RUN python3 -m venv "${VENV_PATH}"

# Set PATH Variable to include venv
ENV PATH="${VENV_PATH}/bin:$PATH"

# Activate venv
RUN source "${VENV_PATH}/bin/activate"

# Install required Packages
RUN --mount=type=cache,mode=0777,target=/var/lib/pip,sharing=locked \
    pip install --cache-dir /var/lib/pip -r "${WEEWX_PATH}/requirements.txt"

# Define Archive File
ARG WEEWX_ARCHIVE="weewx-${WEEWX_VERSION}.tar.gz" # 4.x has .tar.gz extension
#ARG WEEWX_ARCHIVE="weewx-${WEEWX_VERSION}.tgz" # 5.x has .tgz extension
ARG WEEWX_MQTT_ARCHIVE="weewx-mqtt.zip"
ARG WEEWX_INTERCEPTOR_ARCHIVE="weewx-interceptor.zip"

# Change to /tmp
WORKDIR /tmp

# Download Packages
RUN wget -O "${WEEWX_ARCHIVE}" "https://weewx.com/downloads/released_versions/${WEEWX_ARCHIVE}"
RUN wget -O "${WEEWX_MQTT_ARCHIVE}" "https://github.com/matthewwall/weewx-mqtt/archive/master.zip"
RUN wget -O "${WEEWX_INTERCEPTOR_ARCHIVE}" "https://github.com/matthewwall/weewx-interceptor/archive/master.zip"

# Verify Hashes
# ...

# Install Packages
RUN tar xf ${WEEWX_ARCHIVE} --strip-components=1 -C ${WEEWX_PATH}

# Create initial weewx.conf file
RUN mkdir -p "${WEEWX_CONF_PATH}"
#RUN touch "${WEEWX_CONF_PATH}/weewx.conf"

# Install Extensions (WeeWX 4.x)
RUN ${WEEWX_PATH}/bin/wee_extension --install /tmp/${WEEWX_MQTT_ARCHIVE}
RUN ${WEEWX_PATH}/bin/wee_extension --install /tmp/${WEEWX_INTERCEPTOR_ARCHIVE}

# Install Extensions (WeeWX 5.x)
#RUN ${WEEWX_PATH}/bin/weectl extension install /tmp/${WEEWX_MQTT_ARCHIVE}
#RUN ${WEEWX_PATH}/bin/weectl extension install /tmp/${WEEWX_INTERCEPTOR_ARCHIVE}

# Apply Patches
RUN for p in ${PATCHES_PATH}/*.patch; do patch -d/ -p0 < $p; done

# Export Web Port
EXPOSE 8080

# Set PATH Variable to Include Application
ENV PATH="${WEEWX_PATH}/bin:${VENV_PATH}/bin:$PATH"

# Copy and Execute Script for Installation and Initialization of App
COPY docker-entrypoint.sh /opt/
RUN chmod +x /opt/docker-entrypoint.sh
ENTRYPOINT ["/opt/docker-entrypoint.sh"]
