FROM debian:latest

ARG WEEWX_PATH="/opt/weewx"
#ARG WEEWX_HOME_DIR="/home/weewx"
ARG WEEWX_CONF_PATH="/etc/weewx"
ARG VENV_PATH="/opt/venv"

# Create Directories
RUN mkdir -p "${WEEWX_PATH}"
RUN mkdir -p "${WEEWX_CONF_PATH}"
RUN mkdir -p "${VENV_PATH}"

RUN apt-get update
RUN apt-get install -y python3 python3-pip python3-venv bash wget curl unzip libpcap-dev
#RUN apt-get --no-install-recommends -y install rsyslog
RUN apt-get -y install busybox-syslogd
#RUN apk add install rrdtool
RUN apt-get -y install gcc
RUN apt-get -y install python3-dev libstdc++-12-dev patch

# Change Shell
RUN chsh -s /bin/bash root
RUN export SHELL="/bin/bash"
RUN ln -sf /bin/bash /bin/sh

# set ENV to execute startup scripts
ENV ENV /etc/profile
