FROM alpine:latest

ARG WEEWX_PATH="/opt/weewx"
#ARG WEEWX_HOME_DIR="/home/weewx"
ARG WEEWX_CONF_PATH="/etc/weewx"
ARG VENV_PATH="/opt/venv"

# Create Directories
RUN mkdir -p "${WEEWX_PATH}"
RUN mkdir -p "${WEEWX_CONF_PATH}"
RUN mkdir -p "${VENV_PATH}"

# Update Sources
# Install required Packages
RUN --mount=type=cache,mode=0777,target=/var/cache/apk,sharing=locked \
    --mount=type=cache,mode=0777,target=/var/lib/apk,sharing=locked \
    apk update && \
    apk add python3 py3-pip bash wget curl unzip libpcap-dev shadow && \
    apk add inetutils-syslogd && \
    apk add python3-dev libstdc++ patch zlib zlib-dev lzlib libjpeg jpeg jpeg-dev libc++-dev klibc-dev libstdc++-dev && \
    apk add gcc python3-dev musl-dev && \
    apk add freetype freetype-dev

# Not Currently Enabled Packages
#RUN --mount=type=cache,mode=0777,target=/var/cache/apk,sharing=locked \
#    --mount=type=cache,mode=0777,target=/var/lib/apk,sharing=locked \
#    apk update && \
#    apk add --virtual build-deps gcc python3-dev musl-dev && \
#    apk add rsyslog && \
#    apk add install rrdtool

# Change Shell
RUN chsh -s /bin/bash root
RUN export SHELL="/bin/bash"
RUN ln -sf /bin/bash /bin/sh

# set ENV to execute startup scripts
ENV ENV /etc/profile
